name: EventHelper
version: '${project.version}'
main: ru.sparkcraft.eventhelper.EventHelper
api-version: 1.18
authors: [ Spark ]
website: sparkcraft.ru
depend: [ WorldGuard, WorldGuardEvents ]
commands:
  eventhelper:
    description: no
    aliases:
      - e