name: EventHelper
version: '${project.version}'
main: ru.sparkcraft.eventhelper.EventHelper
api-version: 1.20
authors: [ Spark ]
website: sparkcraft.ru
depend: [ WorldGuard, WorldGuardEvents ]
commands:
  eventhelper:
    description: no
    aliases:
      - e
libraries:
  - com.zaxxer:HikariCP:5.1.0